services:
  database:
    image: mariadb:11.3.2
    volumes:
      - database:/var/lib/mysql:rw
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: budgets
      MYSQL_USER: service
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    expose:
      - 3306
    networks:
      custom_net:
    secrets:
      - db_password
      - db_root_password
  dbinit:
    build: dbinit
    depends_on:
      - database
    environment:
      DB_HOST: database
      DB_PORT: 3306
      DB_USER: service
      DB_PASS_FILE: /run/secrets/db_password
      DB_DATABASE: budgets
    networks:
      custom_net:
    secrets:
      - db_password
  backend:
    build: backend
    environment:
      DB_HOST: database
      DB_PORT: 3306
      DB_USER: service
      DB_PASS_FILE: /run/secrets/db_password
      DB_DATABASE: budgets
      WEB_PORT: 3000
      WEB_JWT_SECRET_FILE: /run/secrets/jwt_secret
    expose:
      - 3000
    networks:
      custom_net:
        ipv4_address: 10.5.0.5
    secrets:
      - db_password
      - jwt_secret
  frontend:
    build: frontend
    depends_on:
      - backend
    ports:
      - 8080:80
    networks:
      custom_net:
  #client:
  #  build: dev
  #  networks:
  #    custom_net:

volumes:
  database:

networks:
  custom_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1

secrets:
  db_password:
    file: ./secrets/db_password.txt
  db_root_password:
    file: ./secrets/db_root_password.txt
  jwt_secret:
    file: ./secrets/jwt_secret.txt