# TODO: migrate secrets to be, y'know, actually secret
# TODO: put both frontend and backend behind nginx w/ caching, compression, etc.

services:
  database:
    image: mariadb:11.3.2
    volumes:
      # TODO: use volume once database schema is finalized
      #- database:/var/lib/mysql:rw
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=veryinsecurepassword
      - MYSQL_DATABASE=budgets
      - MYSQL_USER=service
      - MYSQL_PASSWORD=alsoveryinsecurepassword
    #expose:
    #  - 3306
    # DEBUG: don't publish ports to host in prod, only while testing
    ports:
      - 3306
  client:
    build: dev

volumes:
  database: