# TODO: migrate secrets to be, y'know, actually secret
# TODO: put both frontend and backend behind nginx w/ caching, compression, etc.
# TODO: set node environ variables to prod values

services:
  database:
    image: mariadb:11.3.2
    volumes:
      - database:/var/lib/mysql:rw
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=veryinsecurepassword
      - MYSQL_DATABASE=budgets
      - MYSQL_USER=service
      - MYSQL_PASSWORD=alsoveryinsecurepassword
    #expose:
    #  - 3306
    ports:
      - 3306:3306
  dbinit:
    build: dbinit
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_USER=service
      - DB_PASS=alsoveryinsecurepassword
      - DB_DATABASE=budgets
  backend:
    build: backend
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_USER=service
      - DB_PASS=alsoveryinsecurepassword
      - DB_DATABASE=budgets
      - WEB_PORT=3000
      - WEB_JWT_SECRET=zkiPt13TciN3SlUil3Is1fDcbrx5IsALc2KnDiwTVuw=
    #expose:
    #  - 3000
    # DEBUG: don't publish ports to host in prod, only while testing
    ports:
      - 3000:3000
  client:
    build: dev

volumes:
  database: